---
## Run with  Rscript -e "rmarkdown::render('file.Rmd')"
output:
  html_document:
      mathjax: NULL
---

Color Palettes
--------------

In the R `colorspace <https://cran.r-project.org/package=colorspace>`_ package
the palettes are functions returning a set of hex colors as a character list,
the default method how colors are used in R.

The python colorspace package does it slightly different. Palettes are objects
rather than functions which allow to retrieve lists of hex colors using the
``colors()`` method but also provide additiona methods which allow to use the
palettes for plotting in python.

### In R

```{r, echo = TRUE, fig = TRUE, fig.height = .5, fig.width = 4}
# Loading the library
library("colorspace")
# Loading a set of 11 colors
colors <- diverging_hcl(11)
# Plotting a simple color map
par(mar = rep(0,4))
image(matrix(1:11, ncol = 1), col = colors)
```

### In python

```{python, echo = TRUE, fig = TRUE, fig.height = .5, fig.width = 4}
# Loading the module
from colorspace import diverging_hcl, specplot
pal    = diverging_hcl()  # Initialize object
colors = pal.colors(11)   # Retrieve colors
# Plotting a simple color map
specplot(colors, rgb = False, hcl = False)
```


Color Transformation
--------------------

Another difference between the _R_ and the _python_ implementation
is the way how colors are transformed between the different color
spaces.

While the _R_ colorspace packge provides a set of coercing functions (`as`)
_python_ objects provide `.as(...)` methods. The example below shows how
a set of HEX colors are transformed to HCL colors and back.


### In R

```{r, echo = TRUE, fig = TRUE, fig.height = .5, fig.width = 4}
# Loading the library
library("colorspace")
# Prepare a set of 5 colors from the default deverging_hcl palette
colors <- diverging_hcl(5)
print(colors)
# Convert to HCL
HCL <- as(hex2RGB(colors), "polarLUV")
print(HCL)
# Convert back to hex
colors <- hex(as(HCL, "RGB"))
print(colors)
```

### In python

```{python, echo = TRUE, fig = TRUE, fig.height = .5, fig.width = 4}
# Loading the module
from colorspace import diverging_hcl
# Prepare a set of 5 colors from the default diverging_hcl palette
colors = diverging_hcl()(5)
print(colors)
# Convert to HCL
from colorspace.colorlib import hexcols
colors = hexcols(colors)
colors.to("HCL")
print(colors)
# Getting hex colors again by either using the call method
# or transforming the object back to a "hexcols" object.
print(colors())
# Transform ...
colors.to("hex")
print(colors)
```






