---
title: Release Notes
---

## Availability

The software is developed under the GNU Public License (GPL-2 or GPL-3)
on GitHub at <https://github.com/retostauffer/python-colorspace>
and published on PyPI at <https://pypi.org/project/colorspace/>.

Please feel free to use, share, improve, and redistribute the
software under the terms of the GPL. Moreover, bug reports and
suggestions for improvement are very welcome via the GitHub issues
(see [Community guidelines](/community.qmd)).


## Version 0.4.5 (next release)

* Leaving beta, changing to Development Status :: 5 - Production/Stable
* Added swatchplot support for `matplotlib.colors.ListedColormap`s
* Fixed a bug with handling transparency (alpha channel).
* Revamped handling of missing colors; color lists now allow for `None`,
  classes and methods will now also return `None` if a color is invalid
  (outside defined sRGB space if `fixup = True`).
* Removed matplitlib dependency in `check_hex_colors` if not needed.
* Running soft tests (only mandatory packages) and hard tests (additional
    packages for testing extended functionality).
* Fixing a bug in `darken`, `lighten` when using `combined` mixing.
* Extending pytests to adjust for changes in the software.
* Renamed `cvd_emulator` to `cvd_image` to be consistent with _R_.
* Fixing a bug in `diverging_hcl` and `divergingx_hcl` when only
    one color is drawn from the palette.
* Transparency handling for all palettes added and tested.
* Fixing a bug in `divergingx_hcl` where `cmax2` was overwritten by `cmax1` if
    not explicitly set.


## Version 0.4.4 (July 18, 2024)

* Improvements and streamlining in documentation.
* HTML representation of `hexcols` objects when rendered via jupyter
  (reported by @matteoferla in <https://github.com/retostauffer/python-colorspace/issues/7>).
* Fixed a bug in `specplot`, adjusted docstring.
* Added [`hclplot`](/man/colorspace.hclplot.hclplot.qmd).
* Fixed a series of small bugs and extended functionality.
* Updated and extended tests, documentation, CI pipeline (GitHub actions).


## Version 0.4.3 (May 2024)

* First PyPI release on <https://pypi.org/project/colorspace/>.
* Revamped the entire documentation, now using [Quarto](https://quarto.org)
  and still available at <https://retostauffer.github.io/python-colorspace/>.
  Created with help of the new [pyp2qmd](https://retostauffer.github.io/pyp2qmd) package.
* Fixed a series of smaller bugs.
* Adjusted `pytest` to current version.


## Version 0.3.0 (January 2022)

* Removed support for Python 2.
* Adding functionality for swatchplots for `LinearSegmentedColormap` (single object).
* Fixed interactive `choose_palette()` app.
* Added `mixcolor()` for additive color mixing (RGB, CIEXYZ).


## Version 0.1.0 (September 17, 2018)

* Early beta release.
* A wide range of methods are already implemented and roughly
  tested. I've decided to launch it as an early beta release
  to get some feedback from those who use Python more frequently
  than I do! Feel free to report bugs, ideas, or even contribute.
* I'll try to update update the documentation as soon as possible
  and to improve the package itself, if I can find a free time slot.


## Version 0.0.1 (September 1, 2018)

* Development version.
* First implementation of the `colorspace` package in Python.
  This is still an early alpha version, I am currently working
  on better documentation, testing, and getting the necessary
  classes and objects into the package to provide a useful
  toolbox for Python enthusiasts.
