---
title: "Main Classes and Methods"
bibliography: ../references.bib
---

## Overview

At the core of the *colorspace* package are various utilities for computing with
color spaces [@color:Wiki+Colorspace], as the name conveys. Thus, the package helps to
map various three-dimensional representations of color to each other (Ihaka
2003). A particularly important mapping is the one from the perceptually-based
and device-independent color model HCL (Hue-Chroma-Luminance) to standard
Red-Green-Blue (sRGB) which is the basis for color specifications in many
systems based on the corresponding hex codes [@color:Wiki+Webcolors], e.g., in HTML
but also in R. For completeness further standard color models are included as
well in the package. Their connections are illustrated in the following graph:

```{python}
#| echo: true
#| error: true
#| warning: true
#| layout-ncol: 1

from colorspace import palette
pal = palette(["#c3c3c3", "#DD0000"], "Demo")
```


* hclpalettes
* palette
* qualitative_hcl
* diverging_hcl
* sequential_hcl
* rainbow_hcl
* heat_hcl
* terrain_hcl
* diverging_hsv

* tritan
* protan
* deutan
* desaturate

* hcl_palettes
* swatchplot
* specplot
* choose_palette
* cvd_emulator



`defaultpalette` not intended to be used by the user.
Reads the config files (shipped with the python package) and returns all available
default palettes. Called by [`hclpalettes`](../man/colorspace.palettes.hclpalettes.qmd).

[`hclpalettes`](../man/colorspace.palettes.hclpalettes.qmd) serves as the super
class for the following color palettes.

* [`qualitative_hcl`](../man/colorspace.palettes.qualitative_hcl.qmd).
* [`diverging_hcl`](../man/colorspace.palettes.diverging_hcl.qmd).
* [`divergingx_hcl`](../man/colorspace.palettes.divergingx_hcl.qmd).
* [`sequential_hcl`](../man/colorspace.palettes.sequential_hcl.qmd).
* [`rainbow_hcl`](../man/colorspace.palettes.rainbow_hcl.qmd), a convenience palette for qualitative HCL rainbow.
* [`heat_hcl`](../man/colorspace.palettes.heat_hcl.qmd) an HCL approximation of Rs old heat palette.
* [`terrain_hcl`](../man/colorspace.palettes.terrain_hcl.qmd) an HCL approxmation of Rs terrain palette.
* [`diverging_hcl`](../man/colorspace.palettes.diverging_hsv.qmd) an HSV based diverging color palette.

