---
title: "Simulate Color Vision Deficiency"
---

### Description

Transformation of colors by simulating color vision deficiencies, based on
a CVD transform matrix. This function is an interface to the CVD object and
returns simulated colors for deuteranope vision (green-yellow-red
weakness).

See also [protan](colorspace.CVD.protan.qmd), [tritan](colorspace.CVD.tritan.qmd), [desaturate](colorspace.CVD.desaturate.qmd), and
[cvd_emulator](colorspace.cvd_emulator.cvd_emulator.qmd).

### Usage

<pre><code class='language-python'>deutan(cols, severity=1.0, linear=True)</code></pre>

### Arguments

<dl class="pyp-list param-list">
  <dt style = "white-space: nowrap; font-family: monospace; vertical-align: top">
   <code id="colorspace.CVD.deutan:cols">cols</code><code class="argument-class">list, colorobject, matplotlib.colors.LinearSegmentedColormap</code>
  </dt>
 <dd>Single hex color, list of hex colors (str), a matoplotlib cmap, or
a color color object (such as RGB, hexcols, CIELUV).</dd>
  <dt style = "white-space: nowrap; font-family: monospace; vertical-align: top">
   <code id="colorspace.CVD.deutan:severity">severity</code><code class="argument-class">float</code>
  </dt>
 <dd>Severity in `[0., 1.]`. Zero means no deficiency, one
maximum deficiency, defaults to `1.`.</dd>
  <dt style = "white-space: nowrap; font-family: monospace; vertical-align: top">
   <code id="colorspace.CVD.deutan:linear">linear</code><code class="argument-class">bool</code>
  </dt>
 <dd>Should the color vision deficiency transformation be applied to the
linearised RGB coordinates (default)? If `False`, the transformation is applied to the
gamma-corrected sRGB coordinates (as in the Machado et al. 2009 supplementary materials).</dd>
</dl>

### Return

<code>colorobject</code>: Returns an object of the same type as the input object `cols` with
modified colors as people with deuteranomaly see these colors (simulated).

### Examples

```{python}
#| echo: true
#| warning: true
#| error: true
from colorspace import rainbow_hcl, deutan, palette
from colorspace import specplot, swatchplot
# Drawing 100 colors along the HCL rainbow color palette
cols = rainbow_hcl()(100)
specplot(cols);
```

```{python}
#| echo: true
#| warning: true
#| error: true
specplot(deutan(cols));
```

```{python}
#| echo: true
#| warning: true
#| error: true
specplot(deutan(cols, 0.5));
```

```{python}
#| echo: true
#| warning: true
#| error: true
# List of (hex) colors
cols = ["magenta", "red", "orange", "#F2F204", "#6BF204", "#4DA00D"]
deutan(cols);
```

```{python}
#| echo: true
#| warning: true
#| error: true
# Visualize original and simulated color swatches
swatchplot([cols, deutan(cols)],
           show_names = False, figsize = (5, 1.5));
```

```{python}
#| echo: true
#| warning: true
#| error: true
# From palette object
pal = palette(cols, name = "custom palette")
deutan(pal)
```

```{python}
#| echo: true
#| warning: true
#| error: true
# From cmap (returns cmap)
deutan(pal.cmap())
```



