---
title: "Loading colorspace Package Example Data"
---

### Description

The package `colorspace` comes with a few small data sets used
in the Examples and/or the documentation. This function allows
for easy access to these data sets. Note that some data sets
are require `pandas` to be installed.

#### **volcano**: Maunga Whau Volcano

Topographic information on Auckland's Maunga Whau Volcano on 
a 10m x 10m grid. Will return a two-dimensional `numpy.ndarray`
of dimension 61x87 (int64).

#### **HarzTraffic**: Daily Traffic Counts at Sonnenberg

The data set provides daily traffic counts for bikes (motor bikes),
cars, trucks, and other vehicles in the vicinity of Sonnenberg
located in the Harz region in Germany. The data set covers
a period of nearly three years (2021-01-01 to 2023-11-30).

A `pandas.DataFrame` containing 1057 observations (rows) on 16 variables:

* `date` date, the date of the record.
* `yday` int64, the day of the year.
* `bikes` int64, the number of motorcycles on that day.
* `cars` int64, the number of cars on that day.
* `trucks` int64, the number of trucks on that day.
* `others` int64, the number of other vehicles on that day.
* `tempmin` float64, minimum temperature in degrees Celsius.
* `tempmax` float64, maximum temperature in degrees Celsius.
* `temp` float64, mean temperature in degrees Celsius.
* `humidity` int64, mean relative humidity in percent.
* `tempdew` float64, average dewpoint temperature in degrees Celsius.
* `cloudiness` int64, average cloud cover in percent.
* `rain` float64, amount of precipitation in mm (snow and rain).
* `sunshine` int64, sunshine duration in minutes.
* `wind` float64, mean wind speed in meters per second.
* `windmax` float64, maximum wind speed in meters per second.
* `season`: object, local season (sprint, summer, autumn, winter).
* `dow`: int64, numeric day of week (0 = Mon, 6 = Sun).
* `dayofweek`: object, short name of day of week.
* `weekend`: bool, True if the day is Saturday or Sunday, else False.

Weather data: Deutscher Wetterdienst (DWD), Climate Data Center (CDC),
station Wernigerode (5490; Sachsen-Anhalt) w/ location 10.7686/51.8454/233
(lon, lat, alt, EPSG 4326). CC-BY 4.0, available via
<https://opendata.dwd.de/climate_environment/CDC/>.

Traffic data: Bundesanstalt für Strassenwesen (BASt), station Sonnenberg.
CC-BY 4.0, available via <https://www.bast.de>,
<https://www.bast.de/DE/Verkehrstechnik/Fachthemen/v2-verkehrszaehlung/Verkehrszaehlung.html>.


#### **MonthlyHarzTraffic**: Monthly Summary of Traffic Counts at Sonnenberg

Based on the daily data set `HarzTraffic` (see above) but aggregated on
a monthly basis.

A `pandas.DataFrame` containing 35 observations (rows) on 10 variables:

* `year`: int32, year of record.
* `month`: int32, year of record.
* `bikes`: int64, the total number of bikes in that month.
* `cars`: int64, the total number of cars in that month.
* `trucks`: int64, the total number of trucks in that month.
* `others`: int64, the total number of other vehicles in that month.
* `rain`: float64, monthly precipitation sum in mm (snow and rain).
* `temp`: float64, monthly mean temperature in degrees Celsius.
* `sunshine`: int64, monthly average of sunshine per day in minutes.
* `wind`: float64, monthly mean wind speed in meters per second.
* `season`: object, local season (sprint, summer, autumn, winter).

Data source and license: see data set description 'HarzTraffic'.

### Usage

<pre><code class='language-python'>dataset(name)</code></pre>

### Arguments

<dl class="pyp-list param-list">
  <dt style = "white-space: nowrap; font-family: monospace; vertical-align: top">
   <code id="colorspace.datasets.dataset:name">name</code><code class="argument-class">str</code>
  </dt>
 <dd>Name of the data set to be returned.</dd>
</dl>
