---
title: "Convert CIEXYZ to CIELUV."
---

### Description

`X`, `Y`, and `Z` specify the values in the three coordinates of the
CIELAB color space,
`XN`, `YN`, and `ZN` allow to specify additional CIE chromaticities to
specify a specific white point.

### Usage

<pre><code class='language-python'>colorlib.XYZ_to_LUV(X, Y, Z, XN=None, YN=None,<br/>                    ZN=None)</code></pre>

### Arguments

<dl class="pyp-list param-list">
  <dt style = "white-space: nowrap; font-family: monospace; vertical-align: top">
   <code id="colorspace.colorlib.colorlib.XYZ_to_LUV:X">X</code><code class="argument-class">numpy.ndarray</code>
  </dt>
 <dd>escape(Values for the `X` dimension.)</dd>
  <dt style = "white-space: nowrap; font-family: monospace; vertical-align: top">
   <code id="colorspace.colorlib.colorlib.XYZ_to_LUV:Y">Y</code><code class="argument-class">numpy.ndarray</code>
  </dt>
 <dd>escape(Values for the `Y` dimension.)</dd>
  <dt style = "white-space: nowrap; font-family: monospace; vertical-align: top">
   <code id="colorspace.colorlib.colorlib.XYZ_to_LUV:Z">Z</code><code class="argument-class">numpy.ndarray</code>
  </dt>
 <dd>escape(Values for the `Z` dimension.)</dd>
  <dt style = "white-space: nowrap; font-family: monospace; vertical-align: top">
   <code id="colorspace.colorlib.colorlib.XYZ_to_LUV:XN">XN</code><code class="argument-class">None, numpy.ndarray</code>
  </dt>
 <dd>escape(Chromaticity of the white point. If of
length `1`, the white point specification will be recycled if needed.
When not specified (all `None`) a default white point is used.)</dd>
  <dt style = "white-space: nowrap; font-family: monospace; vertical-align: top">
   <code id="colorspace.colorlib.colorlib.XYZ_to_LUV:YN">YN</code>
  </dt>
 <dd>escape(See `XN`.)</dd>
  <dt style = "white-space: nowrap; font-family: monospace; vertical-align: top">
   <code id="colorspace.colorlib.colorlib.XYZ_to_LUV:ZN">ZN</code>
  </dt>
 <dd>escape(See `XN`.)</dd>
</dl>

### Return

Returns corresponding coordinates of CIE chromaticities as
a list of `numpy.ndarray`s of the same length as the inputs (`[L, U, V]`).
